Ext.define('MyApp.model.MonthlyAttendance', {
    extend: 'Ext.data.Model',
    fields:[
        {name:'sheetId', type:'int'},
        {name:'rollNo', type:'int'},
        {name:'studentId', type:'String',mapping:'student_id'},
        {name:'name', type:'string'},
        {name:'d1'},
        {name:'d2'},
        {name:'d3'},
        {name:'d4'},
        {name:'d5'},
        {name:'d6'},
        {name:'d7'},
        {name:'d8'},
        {name:'d9'},
        {name:'d10'},
        {name:'d11'},
        {name:'d12'},
        {name:'d13'},
        {name:'d14'},
        {name:'d15'},
        {name:'d16'},
        {name:'d17'},
        {name:'d18'},
        {name:'d19'},
        {name:'d20'},
        {name:'d21'},
        {name:'d22'},
        {name:'d23'},
        {name:'d24'},
        {name:'d25'},
        {name:'d26'},
        {name:'d27'},
        {name:'d28'},
        {name:'d29'},
        {name:'d30'},
        {name:'d31'}
       ],
     proxy: {
        type: 'rest',
        url : 'mis/attendance/monthly'
    }
  });